version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Cloudwatchlog2s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jlqn2lhhj4xs"
s3_prefix = "Cloudwatchlog2s3"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
